node { 
def mvnHome
stage('Prepare') {
git url: 'git@github.com:keshavkummari/devops.git', branch: 'master'
mvnHome = tool 'maven'
 }
 
stage('Compile') {
 
if (isUnix()) {
 
sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
 
} else {
 
bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
 
}
 
}
 
stage('CodeReview') {
 
if (isUnix()) {
 
sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
 
} else {
 
bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
 
}
 
}
 

stage('Unit Test') {
 
junit '**/target/surefire-reports/TEST-*.xml'
 
archive 'target/*.jar'
 
}
 
stage('Integration Test') {
 
if (isUnix()) {
 
sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean verify"
 
} else {
 
bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean verify/)
 
}
 
}
 
stage('Sonar') {
 
if (isUnix()) {
 
sh "'${mvnHome}/bin/m